### ISSUE TITLE
Carthage Binary Support

### ISSUE THREAD

**Issue by tmspzz** [brightcove/brightcove-player-sdk-ios-player-ui#2]
Would it be possible to add support for [Carthage](https://github.com/Carthage/Carthage) ? The simplest would be to attach a zip with the framework binary as explained [here](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file)

I also suggest the same for the SDK project https://github.com/brightcove/brightcove-player-sdk-ios but there is no option to open issues on that repo.

**Comment by timothyrodgers** [comment]
Hi, tmspzz. I'm sorry for not noticing your issue earlier. In the future, the Brightcove Native Players SDK developer forum (https://groups.google.com/forum/#!forum/brightcove-native-player-sdks) is a better place for posting questions, comments, requests, etc. I've added your request for Carthage support to our backlog and we'll take it under consideration.
